version: '3.8'
services:
  collector:
    build:
      context: .
      dockerfile: src/collector/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
  store:
    build:
      context: .
      dockerfile: src/store/dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app/src
      - store_data:/app/data
  viewer:
    build:
      context: .
      dockerfile: src/viewer/dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./src:/app/src
      - store_data:/app/data
volumes:
  store_data: